implementing exponential-penalty
Datura-ai/smart-scrape pull request #196
Opened 2024-12-19 09:34 UTC by sandrodevdariani

**ticket: https://board.desearch.ai/Implementing-an-Overflow-Period-with-Exponential-Penalties-to-Improve-Validator-Scoring-and-User-Exp-152b8bfdbde980c8833eec02a9860a1a**

**Implementing exponential penalty**: create new file for exponential penalty neurons/validators/penalty/exponential_penalty.py and add class ExponentialTimePenaltyModel

Now, instead of timeout parameter, we are sending the model (NOVA, ORBIT, HORIZON) along with the execution time. Additionally, we are giving the miner an extra 5 seconds. For example, if we choose the NOVA model, the execution time will be automatically calculated as 10 seconds, but the miner will receive 15 seconds to process the task. After that, the validator will receive the max_execution_time from response.max_execution_time and the process_time from the dendrite response. Based on these values, we will calculate the penalty and apply it to the miner.

2024-12-19 19:35 UTC, Chkhikvadze requested changes

2024-12-19 19:35 UTC, Chkhikvadze commented on neurons/validators/scraper_validator.py
> +            model = "NOVA"
Better to have Enum of models and use it, not string

2024-12-19 19:35 UTC, Chkhikvadze commented on neurons/validators/scraper_validator.py
> +                model = "NOVA"
Enum, not just string

2024-12-19 19:35 UTC, Chkhikvadze commented on datura/protocol.py
> +    model: Optional[str] = pydantic.Field(
Better Enum not string

2024-12-19 19:35 UTC, Chkhikvadze commented on neurons/validators/scraper_validator.py
>          self.seed = 1234
remove that field too, no need

2024-12-23 09:26 UTC, okradze commented on neurons/validators/scraper_validator.py
> +            from neurons.validators.api import get_max_execution_time
we can move get_max_execution_time to utils.py if we need in both scraper validator and api and avoid circular import

2024-12-26 12:19 UTC, okradze commented on neurons/validators/scraper_validator.py
> +        synthetic_queries_collection_size = 1
return to 3

2024-12-26 12:22 UTC, okradze commented on neurons/validators/validator.py
> +                await asyncio.sleep(10)
what's this used for?

2024-12-26 12:22 UTC, sandrodevdariani commented on neurons/validators/validator.py
> +                await asyncio.sleep(10)
local testing, its removed now.

2024-12-30 08:45 UTC, merged